export interface StoreConfig {
  storeId: string;
  storeName: string;
  posNumber: string;
  rtf: string;
  phone: string;
  email: string;
  address: string;
  isGasStation: boolean;
  printerConfig?: unknown;
  serverTimezone?: string;
  isGasController: boolean;
  ipFusionController: string;
  claveControlador: string;
  isFusionAssigned: boolean;
  isLealEnabled: boolean;
  urlLeal: string;
  descuentoManual: boolean;
  facturarVariasLineas: boolean;
  screenOnPump: boolean;
  casaMatriz: string;
  name: string;
  rtn: string;
  country: string;
  state: string;
  city: string;
  address1: string;
  address2: string;
  address3: string;
  passAdmin: string;
  turnos: number | null;
  caras: number[];
  d3: string;
  d4: string;
  numberOfTransactionsWaiting: number | null;
  codeCountry: string;
  warningNewInvoiceRanges: number | null;
  warningNewCreditNotesRanges: number | null;
  urlControlador: string;
  blockedForPendingTransactions: boolean;
  debugMode: boolean;
  noConsumidorFinal: string;
  urlSaldo: string;
  validarRFID: boolean;
  validarSaldoCredito: boolean;
  voxIsActive: boolean;
  rangoIndividual: boolean;
  facturacionOrdenada: boolean;
  erp: string;
  urlActualizacion: string;
  urlBaseERP: string;
  turnoManual: boolean;
  calculoInverso: boolean;
  campanas: boolean;
  mostrarBombas?: boolean;
  ocultarBotonOtrasBombas?: boolean;
  numTransaccionesBombas?: number;
  minutosAtrasada?: number;
  mostrarTeclado?: boolean;
  declararMontosIniciales?: boolean;
  nombreBotonFidelizacion: string;
  moneda?: string;
  carpetaMultimedia?: string;
}
