/*
 * F0 — Curación de nombres (español snake_case) y clasificación de tablas.
 * Fuente de verdad para el diccionario de datos y el ETL (F3).
 */

// Clasificación + nombre en español de TODAS las tablas TPV.
// categorias: nucleo | fiscal | catalogo | surtidores | sorteos | log | temporal | legacy
const tables = {
  // ===== NÚCLEO (POS) =====
  Employee: { es: 'empleados', categoria: 'nucleo' },
  Store: { es: 'tiendas', categoria: 'nucleo' },
  'POS Closed Shift': { es: 'turnos', categoria: 'nucleo' },
  TPV_config: { es: 'configuracion_pos', categoria: 'nucleo' },
  Customer: { es: 'clientes', categoria: 'nucleo' },
  Item: { es: 'productos', categoria: 'nucleo' },
  'Sales Price': { es: 'precios_producto', categoria: 'nucleo' },
  Descuentos: { es: 'descuentos', categoria: 'nucleo' },
  'Charge Method': { es: 'metodos_pago', categoria: 'nucleo' },
  HoseFS: { es: 'mangueras', categoria: 'nucleo' },
  'POS Sales Header': { es: 'ventas', categoria: 'nucleo' },
  'POS Sales Line': { es: 'lineas_venta', categoria: 'nucleo' },
  'POS Sales Charge Line': { es: 'pagos_venta', categoria: 'nucleo' },
  POSSalesHeaderLeal: { es: 'ventas_leal', categoria: 'nucleo' },
  'POS Transaction Log': { es: 'registro_transacciones', categoria: 'nucleo' },
  'POS Cash Entries': { es: 'arqueos_caja', categoria: 'nucleo' },
  Motivos: { es: 'motivos', categoria: 'nucleo' },
  TasaCambio: { es: 'tasas_cambio', categoria: 'nucleo' },
  LEAL: { es: 'configuracion_leal', categoria: 'nucleo' },
  StoreShift: { es: 'turnos_tienda', categoria: 'nucleo' },
  StoreShiftConfiguration: { es: 'configuracion_turnos', categoria: 'nucleo' },
  'Item Category': { es: 'categorias_producto', categoria: 'nucleo' },
  FuelAttendant: { es: 'despachadores', categoria: 'nucleo' },

  // ===== FISCAL =====
  'VAT Setup': { es: 'configuracion_isv', categoria: 'fiscal' },
  'No_ Series': { es: 'series', categoria: 'fiscal' },
  'No_ Series Line': { es: 'series_documento', categoria: 'fiscal' },
  'Inv_ Broadcaster': { es: 'emisores_factura', categoria: 'fiscal' },
  'Item Ch_ Methods Restrictions': { es: 'restricciones_metodo_producto', categoria: 'fiscal' },

  // ===== CATÁLOGO / REFERENCIA =====
  Ciudades: { es: 'ciudades', categoria: 'catalogo' },
  Departamentos: { es: 'departamentos', categoria: 'catalogo' },
  'Codigos postales de Honduras': { es: 'codigos_postales', categoria: 'catalogo' },
  'Post Code': { es: 'codigos_postales', categoria: 'catalogo' },
  Idioma: { es: 'idiomas', categoria: 'catalogo' },
  Vendor: { es: 'proveedores', categoria: 'catalogo' },
  'Card Type': { es: 'tipos_tarjeta', categoria: 'catalogo' },
  'Card Restr_ Group Item': { es: 'restricciones_tarjeta', categoria: 'catalogo' },
  'Cust_ Card': { es: 'tarjetas_cliente', categoria: 'catalogo' },

  // ===== SURTIDORES / CONTROLADOR =====
  HoseController: { es: 'mangueras_controlador', categoria: 'surtidores' },
  GradesController: { es: 'grados_controlador', categoria: 'surtidores' },
  GradesFS: { es: 'grados_fs', categoria: 'surtidores' },
  Pump: { es: 'bombas', categoria: 'surtidores' },
  PumpFS: { es: 'bombas_fs', categoria: 'surtidores' },
  PumpsController: { es: 'bombas_controlador', categoria: 'surtidores' },
  PumpsFuelAttendant: { es: 'despachadores_bomba', categoria: 'surtidores' },
  TanksController: { es: 'tanques_controlador', categoria: 'surtidores' },
  TankFS: { es: 'tanques_fs', categoria: 'surtidores' },
  'Fuelling Point': { es: 'puntos_despacho', categoria: 'surtidores' },
  Contadores_Controlador: { es: 'contadores_controlador', categoria: 'surtidores' },
  Turno_Controlador: { es: 'turnos_controlador', categoria: 'surtidores' },
  Dispenser: { es: 'dispensadores', categoria: 'surtidores' },
  DispenserDetail: { es: 'dispensadores_detalle', categoria: 'surtidores' },

  // ===== SORTEOS =====
  Sorteos: { es: 'sorteos', categoria: 'sorteos' },
  SorteosCondiciones: { es: 'condiciones_sorteo', categoria: 'sorteos' },
  Sorteo_Premio: { es: 'premios_sorteo', categoria: 'sorteos' },
  Sorteo_Usuario: { es: 'usuarios_sorteo', categoria: 'sorteos' },

  // ===== LOGS (opcional migrar) =====
  LOG: { es: 'log', categoria: 'log' },
  Log_SubidaDatosTPV: { es: 'log_subida_datos', categoria: 'log' },
  Tpv_Logs: { es: 'log_tpv', categoria: 'log' },
  Tpv_Log_Suceso: { es: 'log_suceso', categoria: 'log' },
  ModificationsRecords: { es: 'registros_modificaciones', categoria: 'log' },
  COMENTARIOS: { es: 'comentarios', categoria: 'log' },

  // ===== TEMPORALES (scratch de reportes — NO migrar) =====
  Temp_Customer: { es: null, categoria: 'temporal' },
  Temp_Item: { es: null, categoria: 'temporal' },
  Temp_SalesPrice: { es: null, categoria: 'temporal' },
  Temp_ItemReference: { es: null, categoria: 'temporal' },
  TempDescuentos: { es: null, categoria: 'temporal' },
  TempDescuentoSP: { es: null, categoria: 'temporal' },
  TempDetailsSPs: { es: null, categoria: 'temporal' },
  TempFilterSPs: { es: null, categoria: 'temporal' },
  TempInvoiceSPs: { es: null, categoria: 'temporal' },
  TempItemReferences: { es: null, categoria: 'temporal' },
  TempRemainingSPs: { es: null, categoria: 'temporal' },
  TempReportSPDefs: { es: null, categoria: 'temporal' },
  TempTotalEfectivoSPs: { es: null, categoria: 'temporal' },
  TempTotalesSPs: { es: null, categoria: 'temporal' },

  // ===== LEGACY / VACÍO (NO migrar) =====
  OCPP_MeterValues: { es: null, categoria: 'legacy' },
  OCPP_Transaciones: { es: null, categoria: 'legacy' },
  ParkingConfig: { es: null, categoria: 'legacy' },
  MaqTabacoConfig: { es: null, categoria: 'legacy' },
  'Manual Discount': { es: null, categoria: 'legacy' },
  'Manual Discount Line': { es: null, categoria: 'legacy' },
  Extension_Ticket: { es: null, categoria: 'legacy' },
  'POS Encuesta': { es: null, categoria: 'legacy' },
  'POS Respuestas': { es: null, categoria: 'legacy' },
  POS_Tarjetas: { es: null, categoria: 'legacy' },
  'POS Extraction_Return': { es: null, categoria: 'legacy' },
  'POS Parked Line': { es: null, categoria: 'legacy' },
  'POS Pump Meters': { es: null, categoria: 'legacy' },
  'POS Sales VAT Specification': { es: null, categoria: 'legacy' },
  'POS Tank Measuring Entries': { es: null, categoria: 'legacy' },
  'ficohsa-tipos': { es: null, categoria: 'legacy' },
  'ficohsa-voucher': { es: null, categoria: 'legacy' },
  'Interface Menus': { es: null, categoria: 'legacy' },
  Shortcut: { es: null, categoria: 'legacy' },
  ShortcutGroups: { es: null, categoria: 'legacy' },
  StoreShortcuts: { es: null, categoria: 'legacy' },
  StoreLines: { es: null, categoria: 'legacy' },
  URLs: { es: null, categoria: 'legacy' },
  Parametros: { es: null, categoria: 'legacy' },
  users: { es: null, categoria: 'legacy' },
  products: { es: null, categoria: 'legacy' },
  sales: { es: null, categoria: 'legacy' },
  Usuario: { es: null, categoria: 'legacy' },
  PurchaseOrders: { es: null, categoria: 'legacy' },
  PurchaseOrdersEntry: { es: null, categoria: 'legacy' },
  Reparacion2: { es: null, categoria: 'legacy' },
  'Sales Line Discount': { es: null, categoria: 'legacy' },
  'Sales Rule & Inv_ Brdc_ Setup': { es: null, categoria: 'legacy' },
  TABs: { es: null, categoria: 'legacy' },
  TABdetail: { es: null, categoria: 'legacy' },
  CostingCodeSAP: { es: null, categoria: 'legacy' },
  'Item Cross Reference': { es: null, categoria: 'legacy' },
  'Item H24': { es: null, categoria: 'legacy' },
  'Item SOLRED Equivalence': { es: null, categoria: 'legacy' },
  ItemReferences: { es: null, categoria: 'legacy' },
  Item_Franquicia: { es: null, categoria: 'legacy' },
  Item_Multibox: { es: null, categoria: 'legacy' },
  'PROM Item Category': { es: null, categoria: 'legacy' },
  'PROM POS Sales Line': { es: null, categoria: 'legacy' },
  PROM_Cab_Reglas_Aplicacion: { es: null, categoria: 'legacy' },
  PROM_Cab_Reglas_Evaluacion: { es: null, categoria: 'legacy' },
  PROM_Cab_Reglas_Generacion: { es: null, categoria: 'legacy' },
  PROM_Promociones: { es: null, categoria: 'legacy' },
  PROM_Reglas_Aplicacion: { es: null, categoria: 'legacy' },
  PROM_Reglas_Eval_Grupo_Cliente: { es: null, categoria: 'legacy' },
  PROM_Reglas_Evaluacion: { es: null, categoria: 'legacy' },
  PROM_Reglas_Fechas: { es: null, categoria: 'legacy' },
  PROM_Reglas_Gener_Charge_Method: { es: null, categoria: 'legacy' },
  PROM_Reglas_Gener_Grupo_Cliente: { es: null, categoria: 'legacy' },
  PROM_Reglas_Generacion: { es: null, categoria: 'legacy' },
  EmployeePresence: { es: null, categoria: 'legacy' },
  'Forma_Pago': { es: null, categoria: 'legacy' },
};

// Mapeo de columnas (original -> español) para las tablas NÚCLEO.
const columns = {
  Employee: {
    Id: 'id', Nombre: 'nombre', PIN: 'pin', Usuario: 'usuario', Perfil: 'perfil',
    Is_active: 'esta_activo', Codigo_RFID: 'codigo_rfid', PasswordHash: 'hash_contrasena',
  },
  Store: {
    StoreID: 'id_tienda', Titulo: 'titulo', Name: 'nombre', RTN: 'rtn', Country: 'pais',
    State: 'estado', City: 'ciudad', Address1: 'direccion_1', Address2: 'direccion_2',
    Address3: 'direccion_3', Phone: 'telefono', Email: 'correo', PassAdmin: 'contrasena_admin',
    Turnos: 'turnos', D3: 'd3', D4: 'd4',
    NumberOfTransactionsWaiting: 'transacciones_pendientes', URLLEAL: 'url_leal',
    isLealEnabled: 'leal_habilitado', CodeCountry: 'codigo_pais', IsGasController: 'es_controlador_gas',
    WarningNewInvoiceRanges: 'aviso_nuevos_rangos_factura', WarningNewCreditNotesRanges: 'aviso_nuevos_rangos_nota_credito',
    IsFusionAssigned: 'fusion_asignado', IPFusionController: 'ip_fusion', Api: 'api',
    MultipleItemsAllowed: 'varias_lineas_permitidas', AllowedToApplyDiscounts: 'descuentos_permitidos',
    BlockedForPendingTransactions: 'bloqueado_transacciones_pendientes', DebugMode: 'modo_depuracion',
    FusionControllerKey: 'clave_fusion', NoConsumidorFinal: 'codigo_consumidor_final', URLSaldo: 'url_saldo',
    ValidarRFID: 'validar_rfid', ValidarSaldoCredito: 'validar_saldo_credito', VoxIsActive: 'vox_activo',
    RangoIndividual: 'rango_individual', FacturacionOrdenada: 'facturacion_ordenada', ERP: 'erp',
    Url_Actualizacion: 'url_actualizacion', URLBaseERP: 'url_base_erp', Turno_Manual: 'turno_manual',
    Calculo_Inverso: 'calculo_inverso', BlockedForPendingPumpTransactions: 'bloqueado_transacciones_bomba',
    BlockedForPendingShiftTransactions: 'bloqueado_transacciones_turno', Sorteos: 'sorteos',
    DeclararMontoInicial: 'declarar_monto_inicial',
  },
  'POS Closed Shift': {
    'POS Transaction ID': 'id_transaccion_pos', 'Gas Station Code': 'id_tienda', 'POS Code': 'codigo_pos',
    Shift: 'turno', idWeekDay: 'id_dia_semana', 'Shift Starting': 'inicio_turno',
    'Shift Ending': 'fin_turno', ImporteContado: 'importe_contado',
    EmployeeName: 'nombre_empleado', MontoInicial: 'monto_inicial',
  },
  TPV_config: {
    'POS Code': 'codigo_pos', ScreenOnPump: 'pantalla_en_bomba', ApplyBlockOnlyPOS: 'bloquear_solo_pos',
    ShowAdvertisingVideo: 'mostrar_video_publicidad', ReimprimirVarios: 'reimprimir_varios',
    FacturarVariasLineas: 'facturar_varias_lineas', DescuentoManual: 'descuento_manual',
    OcultarBotonOtrasDispensadoras: 'ocultar_boton_otras_bombas', OcultarInformacionTurnos: 'ocultar_informacion_turnos',
  },
  Customer: {
    'No_': 'codigo', Name: 'nombre', Address: 'direccion', City: 'ciudad', 'Phone No_': 'telefono',
    'Customer Disc_ Group': 'grupo_descuento', 'Country_Region Code': 'codigo_pais', Blocked: 'bloqueado',
    'VAT Registration No_': 'rtn', 'Post Code': 'codigo_postal', County: 'municipio', 'E-Mail': 'correo',
    'Usual Billing Type': 'tipo_facturacion', Status: 'estado', 'Customer PROM Group': 'grupo_promo',
    'Update Type': 'tipo_actualizacion', DateUpdate: 'fecha_actualizacion', bcid: 'bcid',
    DateofBirth: 'fecha_nacimiento', IdDepartamento: 'id_departamento', IdMunicipio: 'id_municipio',
    Balance_LCY: 'saldo_moneda_local', Balance: 'saldo', 'Customer Posting_ Group': 'grupo_contable',
    'Gen_ Bus_ Posting_ Group': 'grupo_contable_negocio',
  },
  Item: {
    'No_': 'codigo', Description: 'descripcion', 'Unit Price': 'precio_unitario', Blocked: 'bloqueado',
    Picture: 'imagen', 'VAT Prod_ Posting Group': 'grupo_isv', 'Item Category Code': 'codigo_categoria',
    'Product Group Code': 'codigo_grupo', Bonified: 'bonificado',
    'UoM Conversion Factor': 'factor_conversion_um', 'Labels UoM Code': 'codigo_um_etiquetas',
    'Gen_ Pump Ledg_ Entry': 'genera_asiento_bomba', 'Item Disc_ Group': 'grupo_descuento',
    'POS Price Change Allowed': 'permite_cambio_precio', 'PROM Item Category Code': 'codigo_categoria_promo',
    'POS Negative Quantity Allowed': 'permite_cantidad_negativa', BC_ID: 'bc_id', vendorId: 'id_proveedor',
    IsAgeDiscountApplied: 'aplica_descuento_edad',
  },
  'Sales Price': {
    'Item No_': 'codigo_producto', 'Gas Station Code': 'id_tienda', 'Starting Date': 'fecha_inicio',
    'Starting Time': 'hora_inicio', 'Minimum Quantity': 'cantidad_minima', 'Unit Price': 'precio_unitario',
    'Ending Date': 'fecha_fin', 'Ending Time': 'hora_fin', Status: 'estado', Id: 'id',
  },
  Descuentos: {
    codigo_cliente: 'codigo_cliente', codigo_item: 'codigo_producto', porcentaje: 'porcentaje',
    CustomerRTN: 'rtn_cliente', StoreID: 'id_tienda', StartingDate: 'fecha_inicio', EndingDate: 'fecha_fin',
    AmountPerGallon: 'monto_por_galon', AmountPerLiter: 'monto_por_litro',
    ReferenceUnitPrice: 'precio_referencia', EntryMode: 'modo_ingreso', Active: 'activo',
  },
  'Charge Method': {
    Code: 'codigo', Description: 'descripcion', 'Excl_ in Shift Summary': 'excluir_resumen_turno',
    'Used By': 'usado_por', 'Charge Type': 'tipo_cargo', 'Expired in POS': 'vencido_en_pos',
    Invoice: 'factura', Ticket: 'ticket', Credit: 'credito', Referencia: 'referencia',
  },
  LEAL: { user: 'usuario', pass: 'contrasena' },
  HoseFS: {
    HoseID: 'id_manguera', GradeNumber: 'numero_grado', GradeName: 'nombre_grado',
    PricePerUnit: 'precio_unitario', TankIDs: 'ids_tanques', PumpID: 'id_bomba',
    HosePhysicalID: 'id_manguera_fisica', POS: 'pos', CodigoPOS: 'codigo_pos',
    CodigoGenerico: 'codigo_generico', EsVisible: 'visible',
  },
  'No_ Series': { Code: 'codigo', Description: 'descripcion', Iniciales: 'iniciales' },
  'No_ Series Line': {
    'Series Code': 'codigo_serie', 'Line No_': 'numero_linea', 'Gas Station Code': 'id_tienda',
    'POS Code': 'codigo_pos', 'Starting Date': 'fecha_inicio', 'Starting No_': 'numero_inicio',
    'Ending No_': 'numero_fin', 'Warning No_': 'numero_aviso', 'Increment-by No_': 'incremento',
    'Last No_ Used': 'ultimo_numero_usado', Open: 'abierta', 'Last Date Used': 'ultima_fecha_usada',
    CAI: 'cai', 'Rango Desde': 'rango_desde', 'Rango Hasta': 'rango_hasta',
    'Fecha Vence Rango': 'fecha_vence_rango',
  },
  'POS Sales Header': {
    'POS Transaction ID': 'id_transaccion_pos', 'Gas Station Code': 'id_tienda', 'POS Code': 'codigo_pos',
    'Inv_ Broadcaster No_': 'numero_emisor', 'POS Sales Doc_ Type': 'tipo_documento',
    'POS Sales Doc_ No_': 'numero_documento', 'Customer No_': 'codigo_cliente',
    'Sale Date Time': 'fecha_hora_venta', Amount: 'monto', 'Cust_ Card No_': 'numero_tarjeta_cliente',
    'Points Card No_': 'numero_tarjeta_puntos', 'Plate No_': 'placa',
    'Rel_ Sales Document No_': 'documento_relacionado', 'Salesperson Code': 'codigo_vendedor',
    'VAT Reg_ No_': 'rtn_cliente', 'Cust_ Name': 'nombre_cliente', 'Cust_ Name 2': 'nombre_cliente_2',
    'Cust_ Address': 'direccion_cliente', 'Cust_ Address 2': 'direccion_cliente_2',
    'Cust_ Post Code': 'codigo_postal_cliente', 'Cust_ City': 'ciudad_cliente',
    'Cust_ County': 'municipio_cliente', 'Cust_ Country_Reg_ Code': 'codigo_pais_cliente',
    'Billing Type': 'tipo_facturacion', 'Cust_ E-Mail': 'correo_cliente', Comment: 'comentario',
    BC_ID: 'bc_id', 'Line No_': 'numero_linea', SubTotal: 'subtotal', KM: 'kilometraje',
    Orden: 'orden', Placa: 'placa_orden', Chofer: 'chofer', Cambio: 'cambio',
  },
  'POS Sales Line': {
    'POS Transaction ID': 'id_transaccion_pos', 'Gas Station Code': 'id_tienda', 'POS Code': 'codigo_pos',
    'Inv_ Broadcaster No_': 'numero_emisor', 'POS Sales Doc_ Type': 'tipo_documento',
    'POS Sales Doc_ No_': 'numero_documento', 'POS Sales Doc_ Line No_': 'numero_linea_documento',
    'POS Sales Type': 'tipo_venta', 'POS Sales No_': 'numero_venta', Description: 'descripcion',
    Quantity: 'cantidad', 'Unit Price Incl_ VAT': 'precio_unitario_con_isv',
    'Unit Discount Amount': 'monto_descuento_unitario', 'Discount _': 'descuento',
    'Line Discount Amount': 'monto_descuento_linea', 'VAT _': 'isv', VAT_Amount: 'monto_isv',
    'Amount Including VAT': 'monto_con_isv', 'Pump No_': 'numero_bomba',
    'Pump Position No_': 'posicion_bomba', 'Tank No_': 'numero_tanque',
    'Operation Time': 'hora_operacion', 'Item Category Code': 'codigo_categoria', Bonified: 'bonificado',
    Returned: 'devuelto', 'Gen_ Pump Ledg_ Entry': 'genera_asiento_bomba',
    'VAT Prod_ Posting Group': 'grupo_isv', 'Source POS Transaction ID': 'id_transaccion_origen',
    'Source POS Sales Doc_ No_': 'documento_origen', 'Source POS Sales Doc_ Line No_': 'linea_documento_origen',
    'DOMS Trans No_': 'numero_transaccion_doms', Prepayment: 'prepago', Return: 'devolucion',
    'Applies-to Line No_': 'numero_linea_aplicada', 'Fidelity Points': 'puntos_fidelidad',
    idFuelAttendant: 'id_despachador', SaleID: 'id_venta', TaxedAmount: 'monto_gravado',
  },
  'POS Sales Charge Line': {
    'POS Transaction ID': 'id_transaccion_pos', 'Gas Station Code': 'id_tienda', 'POS Code': 'codigo_pos',
    'Charge Line No_': 'numero_linea_pago', 'Charge Method Code': 'codigo_metodo_pago', Amount: 'monto',
    'Payment Card No_': 'numero_tarjeta', Description: 'descripcion',
    'Datos Adicionales': 'datos_adicionales', idFuelAttendant: 'id_despachador',
    TasaCambio: 'tasa_cambio', MontoIngresado: 'monto_ingresado', EsTicket: 'es_ticket',
  },
  POSSalesHeaderLeal: {
    'POS Transaction ID': 'id_transaccion_pos', Id_TransaccionLeal: 'id_transaccion_leal',
    Puntos: 'puntos', PuntosActivos: 'puntos_activos', Tipo: 'tipo', DNI: 'dni',
    Nombre: 'nombre', IDAleatorio: 'id_aleatorio',
  },
  Sorteos: {
    SorteoID: 'id', Nombre: 'nombre', FechaInicio: 'fecha_inicio', FechaFin: 'fecha_fin',
    Activo: 'activo', TextoTicket: 'texto_ticket',
  },
  SorteosCondiciones: {
    CondicionID: 'id', SorteoID: 'id_sorteo', TipoEvaluacion: 'tipo_evaluacion', Operador: 'operador',
    ValorTexto: 'valor_texto', ValorMonto: 'valor_monto', ValorCantidad: 'valor_cantidad',
    ValorRequerido: 'valor_requerido',
  },
  Sorteo_Premio: {
    id: 'id', posSalesDocNo: 'numero_documento_venta', nombre: 'nombre', telefono: 'telefono',
    frecuencia: 'frecuencia', prioridad: 'prioridad', estado: 'estado', eliminado: 'eliminado',
    usuarioId: 'id_usuario', created_at: 'creado_en',
  },
  Sorteo_Usuario: {
    id: 'id', nombre: 'nombre', username: 'usuario', password: 'contrasena', role: 'rol',
    activo: 'activo', created_at: 'creado_en', updated_at: 'actualizado_en',
  },
  Motivos: { Id_motivo: 'id', motivo: 'motivo' },
  TasaCambio: { ID_Tasa_Cambio: 'id', Tasa_Cambio: 'tasa', Fecha: 'fecha' },
  'POS Transaction Log': {
    'POS Transaction ID': 'id_transaccion_pos', 'Gas Station Code': 'id_tienda', 'POS Code': 'codigo_pos',
    'Shift Date': 'fecha_turno', 'Shift No_': 'numero_turno', 'Transaction Type': 'tipo_transaccion',
    'Transaction DateTime': 'fecha_hora_transaccion', Status: 'estado', EmployeeName: 'nombre_empleado',
  },
  'POS Cash Entries': {
    'POS Transaction ID': 'id_transaccion_pos', 'Gas Station Code': 'id_tienda', 'POS Code': 'codigo_pos',
    'Charge Method Code': 'codigo_metodo_pago', 'Charge Method Description': 'descripcion_metodo_pago',
    Amount: 'monto', 'Salesperson Code': 'codigo_vendedor', POSDocNo: 'numero_documento',
    CustomerNo: 'codigo_cliente', Comment: 'comentario',
  },
  'VAT Setup': {
    'VAT Prod_ Posting Group': 'grupo_isv', 'Starting Date': 'fecha_inicio', 'VAT _': 'isv',
    Description: 'descripcion',
  },
  StoreShift: { Shift: 'turno', StartTime: 'hora_inicio', EndTime: 'hora_fin' },
  StoreShiftConfiguration: {
    idWeekDay: 'id', idStore: 'id_tienda', posCode: 'codigo_pos', weekDay: 'dia_semana',
    shiftName: 'nombre_turno', startTime: 'hora_inicio', endTime: 'hora_fin',
    isActive: 'activo', level: 'nivel',
  },
  'Item Category': {
    Code: 'codigo', Description: 'descripcion', 'Item Category Type': 'tipo_categoria',
    'Update Type': 'tipo_actualizacion', DateUpdate: 'fecha_actualizacion',
  },
  FuelAttendant: {
    GasStationCode: 'id_tienda', POSCode: 'codigo_pos', idFuelAttendant: 'id_despachador',
    Nombres: 'nombres', Apellidos: 'apellidos', DNI: 'dni',
  },
};

// Columnas que son flags (int/tinyint/bit) y deben mapearse a boolean.
const booleanColumns = new Set([
  'Employee.Is_active',
  'Store.isLealEnabled', 'Store.IsGasController', 'Store.IsFusionAssigned',
  'Store.MultipleItemsAllowed', 'Store.AllowedToApplyDiscounts', 'Store.BlockedForPendingTransactions',
  'Store.DebugMode', 'Store.ValidarRFID', 'Store.ValidarSaldoCredito', 'Store.VoxIsActive',
  'Store.RangoIndividual', 'Store.FacturacionOrdenada', 'Store.Turno_Manual', 'Store.Calculo_Inverso',
  'Store.BlockedForPendingPumpTransactions', 'Store.BlockedForPendingShiftTransactions',
  'Store.Sorteos', 'Store.DeclararMontoInicial',
  'TPV_config.ScreenOnPump', 'TPV_config.ApplyBlockOnlyPOS', 'TPV_config.ShowAdvertisingVideo',
  'TPV_config.ReimprimirVarios', 'TPV_config.FacturarVariasLineas', 'TPV_config.DescuentoManual',
  'TPV_config.OcultarBotonOtrasDispensadoras', 'TPV_config.OcultarInformacionTurnos',
  'Customer.Blocked',
  'Item.Blocked', 'Item.Bonified', 'Item.Gen_ Pump Ledg_ Entry', 'Item.POS Price Change Allowed',
  'Item.POS Negative Quantity Allowed', 'Item.IsAgeDiscountApplied',
  'Descuentos.Active',
  'Charge Method.Excl_ in Shift Summary', 'Charge Method.Expired in POS',
  'Charge Method.Invoice', 'Charge Method.Ticket', 'Charge Method.Credit', 'Charge Method.Referencia',
  'HoseFS.EsVisible',
  'No_ Series Line.Open',
  'Sales Price.Status',
  'POS Transaction Log.Status',
  'POS Sales Line.Bonified', 'POS Sales Line.Returned', 'POS Sales Line.Gen_ Pump Ledg_ Entry',
  'POS Sales Line.Prepayment', 'POS Sales Line.Return',
  'POS Sales Charge Line.EsTicket',
  'Sorteos.Activo', 'Sorteo_Premio.eliminado', 'Sorteo_Usuario.activo',
  'StoreShiftConfiguration.isActive',
  'FuelSession.WasFuelling', 'FusionSales.IsInvoiced',
]);

// FusionController
const fusionTables = {
  FuelSession: { es: 'sesiones_surtidor' },
  FusionSales: { es: 'ventas_combustible' },
  FusionSalesRetry: { es: 'reintentos_venta_combustible' },
  ReaderPumpMapping: { es: 'mapeo_lector_bomba' },
};

const fusionColumns = {
  FuelSession: {
    Id: 'id', PumpId: 'id_bomba', RaspberryId: 'id_raspberry', State: 'estado',
    StartEmployeeId: 'id_empleado_inicio', StartEmployeeName: 'nombre_empleado_inicio',
    StartTagTime: 'hora_inicio', EndEmployeeId: 'id_empleado_fin',
    EndEmployeeName: 'nombre_empleado_fin', EndTagTime: 'hora_fin', Hose: 'manguera',
    SaleId: 'id_venta', WasFuelling: 'fue_despacho',
  },
  FusionSales: {
    SaleID: 'id_venta', PosNumber: 'numero_pos', PumpNumber: 'numero_bomba',
    HoseNumber: 'numero_manguera', Amount: 'monto', PPU: 'precio_unitario', Volume: 'volumen',
    FinalVolumeTotal: 'volumen_final', InitialVolumeTotal: 'volumen_inicial',
    PaymentType: 'tipo_pago', PaymentInfo: 'info_pago', CompensatedTemperature: 'temperatura_compensada',
    ShiftID: 'id_turno', GradeNr: 'numero_grado', PriceLevel: 'nivel_precio',
    TypeOfTransaction: 'tipo_transaccion', DateOfTransaction: 'fecha_transaccion',
    TimeOfTransaction: 'hora_transaccion', PresetAmount: 'monto_preestablecido',
    PaymentAlarm: 'alarma_pago', ATCVO: 'atcvo', AVGTM: 'avgtm', ATCIVO: 'atcivo', ATCFVO: 'atcfvo',
    IsInvoiced: 'facturada', Date: 'fecha',
  },
  FusionSalesRetry: {
    vox_sale_id: 'id_venta_vox', payload: 'payload', retry_count: 'intentos',
    last_attempt: 'ultimo_intento', error_message: 'mensaje_error',
  },
  ReaderPumpMapping: {
    Id: 'id', ReaderPath: 'ruta_lector', PumpId: 'id_bomba', RaspberryId: 'id_raspberry',
  },
};

module.exports = { tables, columns, booleanColumns, fusionTables, fusionColumns };
